### ISSUE TITLE
Not working with laravel/breeze-vue

### ISSUE THREAD

**Issue by ivancukns** [festusiyere/sweet-modal-vue-3#1]
Hey there, I appreciate you ported this library to work with vue3.
However, it doesnt seem to work with laravel/breeze-vue (v 1.11.1)

Nothing gets rendered, I just get to see  at the place where I used this component.

Any chance you have an idea how to get it to work? Thanks!

**Comment by ivancukns** [comment]
I have more details.
after doing this: npm install sweet-modal-vue-3

I didnt get all the files, there arent any components in that package, so it cant possibly work.

For anyone who runs into this problem, I just copy/pasted the SweetModel.vue from the old Vue2 version into my local components directory, and it works without problems.

**Comment by festusiyere** [comment]
What version of vue are you using?

**Comment by festusiyere** [comment]
I'll look into this and push a fix soonest

**Comment by festusiyere** [comment]
This has been fixed in [this](https://github.com/festusiyere/sweet-modal-vue-3/pull/7) PR
