### ISSUE TITLE
Allow for component installation

### ISSUE THREAD

**Issue by dniccum** [festusiyere/sweet-modal-vue-3#5]
Per #4, the only way this plugin will work is via global registration:

```es6
import SweetModal from 'sweet-modal-vue-3';
const Vue = createApp({});
Vue.use(SweetModal);
```

While this will work for small applications, it is not efficient for larger applications to take advantage of tree shaking and dynamic imports.

**Comment by festusiyere** [comment]
Hi @dniccum this has been fixed in [this](https://github.com/festusiyere/sweet-modal-vue-3/pull/7) PR
